import os
import json


def main():
    result = []
    for id, filename in enumerate(os.listdir("public/audio")):
        print()
        result.append(
            {
                "id": id,
                "title": filename[0:-4].replace("-", " "),
                "author": "neverlane",
                "cover": "/covers/track-by-neverlane_new.jpg",
                "decription": "wntn music <3",
                "song": f"/audio/{filename}"
            }
        )
    with open("src/assets/songs.ts", "w") as f:
        f.write(
            f"/** This file is generated by generate-songs-ts.py. PLEASE DO NOT EDIT */\nexport const Songs = {json.dumps(result, indent=2)};"
        )

if __name__ == "__main__":
    main()
